#!/bin/bash

gpio mode 2 out
gpio write 2 1
gpio write 2 0
gpio mode 2 in

# gpio mode 17 out
# sleep 0.1
# gpio write 17 1
# sleep 0.1
# gpio write 17 0
# sleep 0.1
# gpio mode 17 in
# sleep 0.1




